### ISSUE TITLE
AWS Integration.

### ISSUE THREAD

**Issue by dipasqualew** [photion/product-management#1]
Major feature. Integrates Photion with AWS.

Tracked by:

- [x] photion/integration-aws#1
- [x] photion/webapp-admin#13
- [x] photion/webapp-admin#14
